{
 "title": "Performance with dnsperf",
 "tags": [ "dnsperf" ],
 "time": { "from": "2025-11-30T00:41:36.895Z", "to": "2025-11-30T00:44:49.856Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dnsperf_run_time_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Options",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dnsperf_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(dnsperf_queries_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "irate(dnsperf_queries_completed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "completed"
    },
    {
     "expr": "irate(dnsperf_queries_lost_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "lost"
    }
   ]
  },
  {
   "title": "Packet Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "last_over_time(dnsperf_packet_size_request_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "request"
    },
    {
     "expr": "last_over_time(dnsperf_packet_size_response_bytes{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dnsperf_latency_bucket{instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dnsperf_latency_bucket{instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dnsperf_latency_bucket{instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(dnsperf_response_codes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}